### PR TITLE
Add LICENSE file and remove unnecessary include.

### PR DESCRIPTION
**Pull request by rsesek**
These issues came up during http://ag/693189.

### CODE REVIEW

**Comment by kees** [comment]
I'd actually like to see this licensed GPLv2 so it can be added to the upstream Linux kernel self-tests directory...

**Comment by rsesek** [comment]
I really have no opinion other than the existing files use the Chromium BSD license. Could we dual-license it?

**Comment by rsesek** [comment]
To put another way, this code is _already_ BSD licensed based on the file headers, and so it should have a corresponding required LICENSE file. Changing the license is fine (or dual-licensing) is fine, but probably out of scope for this review.

**Comment by redpig** [comment]
Let's add the licensing needed for the kernel sep.

**Pull request merged**
